package com.revature.models;

import java.io.Serializable;

public class AccountType implements Serializable{
	
	//track what kind of account is being created
	//options are Checking or Savings
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int typeId; // primary key
	private String type; // not null, unique
	
	public AccountType() {
		super();
		// TODO Auto-generated constructor stub
	}


//	void AccountType (int typeId, String type) {
//		//this will tell us the account number and if it's checking/savings
//		
//	}

	//this one was generated by the IDE
	public AccountType(int typeId, String type) {
		super();
		this.typeId = typeId;
		this.type = type;
	}


	public int getTypeId() {
		return typeId;
	}


	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}


	public String getType() {
		return type;
	}


	public void setType(String type) {
		this.type = type;
	}


	@Override
	public String toString() {
		return "AccountType [typeId=" + typeId + ", type=" + type + "]";
	}
	
	
}
